export const Permissions = {
  DASHBOARD_VIEW: "dashboard.view",
  REPORTS_VIEW: "reports.view",
  PHASE2_VIEW: "phase2.view",

  FLEET_VIEW: "fleet.view",
  FLEET_MANAGE: "fleet.manage",
  FLEET_DELETE: "fleet.delete",
  FLEET_DOCUMENTS_VIEW: "fleet.documents.view",
  FLEET_DOCUMENTS_MANAGE: "fleet.documents.manage",
  DRIVERS_VIEW: "drivers.view",
  DRIVERS_MANAGE: "drivers.manage",
  DRIVERS_DELETE: "drivers.delete",
  TRIPS_VIEW: "trips.view",
  TRIPS_MANAGE: "trips.manage",
  TRIPS_STATUS_UPDATE: "trips.status.update",
  TRIPS_DELETE: "trips.delete",
  TRIPS_EXPENSES_VIEW: "trips.expenses.view",
  TRIPS_EXPENSES_MANAGE: "trips.expenses.manage",
  TRIPS_PODS_VIEW: "trips.pods.view",
  TRIPS_PODS_MANAGE: "trips.pods.manage",
  DRIVER_SETTLEMENTS_VIEW: "driver.settlements.view",
  BILLING_CUSTOMERS_VIEW: "billing.customers.view",
  BILLING_CUSTOMERS_MANAGE: "billing.customers.manage",
  BILLING_INVOICES_VIEW: "billing.invoices.view",
  BILLING_INVOICES_MANAGE: "billing.invoices.manage",
  BILLING_EXPORT: "billing.export",

  ROLES_VIEW: "roles.view",
  ROLES_MANAGE: "roles.manage",
  USERS_VIEW: "users.view",
  USERS_MANAGE: "users.manage",
  USERS_RESET_PASSWORD: "users.reset_password",
  AUDIT_VIEW: "audit.view",
  SETTINGS_VIEW: "settings.view",
  SETTINGS_MANAGE: "settings.manage",
  BRANCHES_MANAGE: "branches.manage",
};
